### ISSUE TITLE
no_std?

### ISSUE THREAD

**Issue by birkenfeld** [jonas-schievink/pkg-version#2]
Is it possible for this crate to become `no_std` compatible?

**Comment by jonas-schievink** [comment]
Yeah, this should be trivial to do!

**Comment by birkenfeld** [comment]
Awesome!

**Comment by jonas-schievink** [comment]
I've released 0.1.1 containing this, let me know if it works

**Comment by birkenfeld** [comment]
Yep, perfectly.
